---
# Source: health-diary/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-microk8s-health-diary
  labels:
    helm.sh/chart: health-diary-0.1.0
    app.kubernetes.io/name: health-diary
    app.kubernetes.io/instance: local-microk8s
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: health-diary/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: local-microk8s-health-diary
  labels:
    helm.sh/chart: health-diary-0.1.0
    app.kubernetes.io/name: health-diary
    app.kubernetes.io/instance: local-microk8s
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: health-diary
    app.kubernetes.io/instance: local-microk8s
---
# Source: health-diary/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-microk8s-health-diary
  labels:
    helm.sh/chart: health-diary-0.1.0
    app.kubernetes.io/name: health-diary
    app.kubernetes.io/instance: local-microk8s
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: health-diary
      app.kubernetes.io/instance: local-microk8s
  template:
    metadata:
      labels:
        helm.sh/chart: health-diary-0.1.0
        app.kubernetes.io/name: health-diary
        app.kubernetes.io/instance: local-microk8s
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: local-microk8s-health-diary
      containers:
        - name: health-diary
          image: "ghcr.io/mornemaritz/health-diary/health-diary-ui:v0.10.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
---
# Source: health-diary/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "local-microk8s-health-diary-test-connection"
  labels:
    helm.sh/chart: health-diary-0.1.0
    app.kubernetes.io/name: health-diary
    app.kubernetes.io/instance: local-microk8s
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['local-microk8s-health-diary:3000']
  restartPolicy: Never
